### ISSUE TITLE
extra single quote in URL for datetime 

### ISSUE THREAD

**Issue by phanak-sap** [SAP/odfuzz#40]
sample URL part: `FlightDate gt datetime''7851-03-24T05:08:23''`

**Comment by prashdsouza** [comment]
We have 2 different cases here. For that I am copying 2 fuzzed urls with datetime type. First url fine and the 2nd one has extra single quote.


FlightDate=datetime'8566-04-22T04:37:22')/BookingSet?$orderby=BookingId asc&$filter=BookingId ge 'æ>§7ø²Úd' and CustomerId ge 'þ' or CustomerId ne 'l' or BookingId eq '' or replace(BookingId, '2=J'

FlightConnections?$filter=FlightDate eq datetime''5386-08-05T08:40:33'' or AirportFrom ne 'Í_û' and length(AirlineID) eq 1410601072 and tolower(FlightNumber) eq 'R?' or FlightNumber ne '©'&$expand=BookingSet/BookingExtension

**Comment by lubosmj** [comment]
It seems like other data types (Edm.Binary, Edm.Guid, Edm.Time, Edm.DateTimeOffset) are affected as well. Their representations share the same structure -- a prefix and actual data enclosed in single quotes:

```
binary'[A-Fa-f0-9][A-Fa-f0-9]*'
datetime'yyyy-mm-ddThh:mm[:ss[.fffffff]]'
time'<timeLiteral>'
datetimeoffset'<dateTimeOffsetLiteral>'
```

The problem here is that strings generated by ODfuzz may contain special characters. These special characters need to be properly encoded before sending them to a server. Because of that, ODfuzz replaces a single quote with double quotes (try to create a request which contains only one single quote; you will notice that a server cannot properly interpret the request; on the other hand, strings with a pair of single quotes are handled without any problems), like so: https://github.com/SAP/odfuzz/blob/master/odfuzz/fuzzer.py#L1245-L1253

If I understand it correctly, ODfuzz is no longer used for sending HTTP requests. It just creates a bunch of queries which are managed separately afterwards. Still, I think we cannot delete the functions/methods which normalize generated strings. Random strings will always contain special characters. By any means, It would be almost impossible from the sender's perspective to determine which parts of queries require the encoding. I propose to move the functions/methods, which replace special characters, to the generators and mutators. How does that sound? This is definitely a design flaw.

**Comment by phanak-sap** [comment]
> If I understand it correctly, ODfuzz is no longer used for sending HTTP requests

It is not true. 

Normal use case is same as you know/wrote - run trough CLI, call external server and store some data in Mongo. 

Secondary, minor, use case is what @prashdsouza wanted - run fuzzer as "library URL generator only". All networking is on his side (i.e. java code). Check #37 for details what has been split. The test_url_generator_only.py is sample of such usage. 

When I enabled such usage, I expected that URL generated by Builder class is valid  - and Dispatcher class is only handling HTTP things, not URL itself. If anything relevant to URL building happens outside the Queryable (in the Dispatcher), then this will be reproducible only in second usage.

I need to check this to be sure against some live service with  Edm.Binary, Edm.Guid, Edm.Time, Edm.DateTimeOffs, with the normal use case

**Comment by phanak-sap** [comment]
Yes, this line is the root cause for the behavior (generators and mutators both remains in format `datetime'7088-11-17T11:57:51' `https://github.com/SAP/odfuzz/blob/c8bfe9eaf8f3f97398cbad6eff50e0feb13a9f8b/odfuzz/fuzzer.py#L1252

What I am quite puzzled about:

1) this part...
> Because of that, ODfuzz replaces a single quote with double quotes (try to create a request which contains only one single quote; you will notice that a server cannot properly interpret the request;... 

..may mean only that this method works fine when against SAP odata gateway - since we use it without any problem there with these URLs generated. But @prashdsouza is executing odfuzz against java based odata service, which can handle urls differently

1.1) But if this is true, it may also means that the bug is actually in the java odata service URL handling @prashdsouza uses. I have run all URL generated by the `test_expected_integration_sample` - which has datetime metadata and reproduce thhe behavior with double quotes in filter - trough standard python library urllib.parse and none URL was marked as invalid (no ValueError exception). 

1.2) why this special character replace happens in filter part but not in the entity part in the first URL provided? Isn't that bug as well?
`FlightDate=datetime'8566-04-22T04:37:22')/BookingSe...`

2) the topic of current  URL encoding in odfuzz

2.1) why we don't replace ' character with %27, like all other cases in the method? 

2.2) or even when the URL is "finished", why not offload the proper encoding to standard library, e.g. https://docs.python.org/3/library/urllib.parse.html#url-quoting , instead of calling `replace_special_characters` for each option in the url part? It may be some design decision I don't know - but the URL generation part in fuzzer.py has not tests yet anyway that would document this somehow.

**Comment by lubosmj** [comment]
I responded inline.

> 1.1) But if this is true, it may also means that the bug is actually in the java odata service URL handling @prashdsouza uses. I have run all URL generated by the `test_expected_integration_sample` - which has datetime metadata and reproduce thhe behavior with double quotes in filter - trough standard python library urllib.parse and none URL was marked as invalid (no ValueError exception).

Encoded URLs themselves are not in a wrong format. If no exception was raised during your testing, it means that the URLs were correctly encoded, however, they are not semantically equivalent in terms of OData protocol.

> 1.2) why this special character replace happens in filter part but not in the entity part in the first URL provided? Isn't that bug as well?
> `FlightDate=datetime'8566-04-22T04:37:22')/BookingSe...`

It seems like I did not take into consideration the fact that navigation properties need to be encoded too. The fuzzer generates strings like this:
Sales_Totals_by_Amounts(OrderID=1123468816,CompanyName='°-z£ôPZ‡~…o+')

There is clearly not encoded '+'.

> 2.1) why we don't replace ' character with %27, like all other cases in the method?

Because you have to use a pair of single quotes. It is not all about encoding only. Try out the following URLs (notice the missing single quote in the second example):
1. https://services.odata.org/V2/Northwind/Northwind.svc/Employees?$filter=LastName%20eq%20%27%27%27Davolio%27
2. https://services.odata.org/V2/Northwind/Northwind.svc/Employees?$filter=LastName%20eq%20%27%27Davolio%27

The service returns the error "Syntax error at position 21." for the latter one.

> 2.2) or even when the URL is "finished", why not offload the proper encoding to standard library, e.g. https://docs.python.org/3/library/urllib.parse.html#url-quoting , instead of calling `replace_special_characters` for each option in the url part? It may be some design decision I don't know - but the URL generation part in fuzzer.py has not tests yet anyway that would document this somehow.

Yes, this definitely makes a sense. We should utilize some urllib function for this. Note that we are not encoding every URL part. We do encode just property values. Moving such an encoding (normalization) directly to generators/mutators can solve the issue.
